---
- name: Get current default zone
  shell: firewall-cmd --get-default-zone
  register: default_zone
  changed_when: False
  when: ansible_facts.services.firewalld.state == "started"

- name: Get current default zone
  shell: firewall-offline-cmd --get-default-zone
  register: default_zone
  changed_when: False
  when: ansible_facts.services.firewalld.state != "started"

- name: Set default zone
  shell: firewall-cmd --set-default-zone={{ shhirose_firewalld.default_zone }}
  when:
   - shhirose_firewalld.default_zone is defined
   - default_zone.stdout != shhirose_firewalld.default_zone
   - ansible_facts.services.firewalld.state == "started"

- name: Set default zone
  shell: firewall-offline-cmd --set-default-zone={{ shhirose_firewalld.default_zone }}
  when:
   - shhirose_firewalld.default_zone is defined
   - default_zone.stdout != shhirose_firewalld.default_zone
   - ansible_facts.services.firewalld.state != "started"
