---
- name: populate service facts
  service_facts:

- include: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "RedHat"
  tags:
    - firewalld
    - system
    - security
    - install

- include: "setup.yml"
  tags:
    - firewalld
    - security
    - setup

- shell: firewall-cmd --list-all-zones
  when: ansible_facts.services.firewalld.state == "started"
  changed_when: False
  tags:
    - firewalld

- shell: firewall-offline-cmd --list-all-zones
  when: ansible_facts.services.firewalld.state != "started"
  changed_when: False
  tags:
    - firewalld
