---
- name: Set rich rule
  firewalld:
    rich_rule: "{{ item.rule }}"
    zone: "{{ item.zone | default(omit) }}"
    immediate: "{{ item.immediate | default(ansible_facts.services.firewalld.state == 'started') }}"
    offline: "{{ item.offline | default(ansible_facts.services.firewalld.state != 'started') }}"
    permanent: "{{ item.permanent | default(False) }}"
    state: "{{ item.state }}"
  with_items: "{{ shhirose_firewalld.rich_rules | default([]) }}"

